### ISSUE TITLE
Knob issue in ie11

### ISSUE THREAD

**Issue by Zohaibaig** [Venturocket/angular-slider#13] opened 2014-03-13 06:38 UTC
First thank you for making this plugin.
i am facing issue ,knob is not moving with cursor. when trying to drag  not move in ie11 
working awesome on firedox and chrome ,

see example here and open into ie11
http://mestrosoft.com/test/angular_slider/bower_components/venturocket-angular-slider/example.html

**Comment by drgould** [comment] 2014-03-13 21:01
Which version of windows are you using?

**Comment by Zohaibaig** [comment] 2014-03-14 05:03
i am using window 8.1

**Comment by Zohaibaig** [comment] 2014-03-19 11:42
drgould  I am waiting your response.

**Comment by drgould** [comment] 2014-03-19 17:04
Sorry, I haven't had much time to figure this out. From my brief testing it looks like the pointer events MS uses in IE10/11 are reporting incorrect pointer positions (or possibly no positions at all). I should have some time today to look at it.

**Comment by drgould** [comment] 2014-03-20 00:14
The fix for this is up.

For future reference:
For once IE (10+) was ahead of the curve being the first major browser to adopt pointer events to unify mouse, touch, and pen events into a single set of events (MSPointerDown/Move/Up in IE10 and pointerdown/move/up in IE11). While implementing it was a step forward, they took a massive step back in not passing the normal event attributes along (such as the current position of the pointer, which the slider relies on). As such, the fix was simply to disable those "special" events and fall back on angular's built-in $swipe (which was being used for every other browser).

So the good news is the issue is fixed. The bad news, however, is MS took the proverbial ball and dropped it. What's new?

**Closed as completed by drgould** 2014-03-20 00:14 UTC
Labels: bug

**Comment by Zohaibaig** [comment] 2014-03-20 05:20
issue is resolved thankyou very much.
