### ISSUE TITLE
Not working in ng-repeat

### ISSUE THREAD

**Issue by tjphilli** [Venturocket/angular-slider#7] opened 2014-02-24 06:17 UTC
I have sliders in directives that are being generated via ng-repeat. When I put the directives in directly it works fine, but as soon as I consolidate in ng-repeat, the values are fine but the "knob" and all labels are all the way to the left. I have tried making the ng-repeat <div a direct child of <body, so I know it's not a weird display issue stemming from a container element.

Thanks!
![image](https://f.cloud.github.com/assets/1687500/2243042/a45fac16-9d1b-11e3-80ee-ae0cfd233d6a.png)

**Comment by drgould** [comment] 2014-02-24 17:46
This is a duplicate of #2. I have a fix for this, but I'm currently in the process of refactoring and adding a few other requested features before I push it up.

**Closed as completed by drgould** 2014-02-24 17:46 UTC

**Comment by tjphilli** [comment] 2014-02-24 19:31
Okay awesome. In the meantime, is there anything you'd recommend doing to get it working for me for the time being?

**Comment by drgould** [comment] 2014-02-24 20:42
Here's a hack solution: http://plnkr.co/edit/RL5AnB?p=info

Basically, create an ng-template that includes the slider and ng-include it in the ng-repeat. Here's the full discussion: 24128685ba8351602930afee11f291db0d3d3ebd

**Comment by tjphilli** [comment] 2014-02-24 20:43
Awesome, thank you!!

**Comment by sentient** [comment] 2014-03-27 03:07
When I continue to define the floor and ceiling inside the same template pattern it fails again

http://plnkr.co/edit/3k8YAk8EgB8HnRuRq18s

Do you know of a workaround for this as well?

**Comment by sentient** [comment] 2014-03-27 03:48
If it also getting problematic when you have an ng-repeat  with an inner ng-switch-on.

The ng-switch with a slider is not initialized properly as well.

**Comment by drgould** [comment] 2014-03-28 00:08
First of all, that plunkr is using a version of the slider from 6 months ago. The newest version doesn't require you to define the slider in a template to use it in an ng-repeat, however, it does require angular v1.2.x.

It looks like you're passing the floor and ceiling as variables not values (i.e. it should be `floor="{{ value.floor }}"`, not `floor="value.floor"`).
